Add solidus_auth_devise
Fixes

```
  An error occurred while loading spec_helper.
  Failure/Error: Rails.application.initialize!

  NoMethodError:
    undefined method `devise_for' for #<ActionDispatch::Routing::Mapper:0x000055986b023a60>
  # ./config/routes.rb:6:in `block in <top (required)>'
  # ./config/routes.rb:3:in `<top (required)>'
  # ./spec/dummy/config/environment.rb:5:in `<top (required)>'
  # ./spec/spec_helper.rb:15:in `require'
  # ./spec/spec_helper.rb:15:in `<top (required)>'
```