Copy FillAddressFields
Fixes

```
  1) Checkout without payment being required allow a visitor to checkout as guest, without registration
     Failure/Error: fill_addresses_fields_with(address)

     NoMethodError:
       undefined method `fill_addresses_fields_with' for #<RSpec::ExampleGroups::Checkout::WithoutPaymentBeingRequired:0x00007f8714d278d0>
     # ./spec/features/checkout_spec.rb:63:in `block (3 levels) in <top (required)>'
```