Inline monkey_patches variable
Fixes "NameError: undefined local variable or method `monkey_patches'
for #<Rails::Generators::AppGenerator>" when installing template.

Use `Rails.root.join` instead of embedding `Rails.root` in a string to
prevent the root path from being written in the `application.rb` file.