[FIXED] Require rspec-rails ~> 4.0.0.beta3 before running solidus_starter_frontend
It doesn't seem possible for RspecGenerator to install RSpec and then
load RSpec to invoke the `rspec:install` task.

Without rspec-rails, the following error would appear when
SolidusStarterFrontendGenerator tries to invoke `rspec:install`:

```
bundler: failed to load command: solidus_starter_frontend (/home/gsmendoza/repos/local/solidus_starter_frontend--sandbox-generated--bundle/ruby/2.6.0/bin/solidus_starter_frontend)
RuntimeError: Missing Thor class for invoke rspec:install
  /home/gsmendoza/repos/nebulab/solidus_starter_frontend/lib/generators/solidus_starter_frontend/solidus_starter_frontend_generator.rb:44:in `install'
  /home/gsmendoza/repos/local/solidus_starter_frontend--sandbox-generated--bundle/ruby/2.6.0/gems/railties-6.1.4.1/lib/rails/generators.rb:275:in `invoke'
  /home/gsmendoza/repos/nebulab/solidus_starter_frontend/exe/solidus_starter_frontend:9:in `<top (required)>'
```